
create extension if not exists pgcrypto;
create table if not exists public.players (
 player_id uuid primary key, player_name text not null, best_score bigint not null default 0,
 level integer not null default 1, rebirths integer not null default 0,
 game_version text not null default 'unknown', created_at timestamptz not null default now(),
 last_seen timestamptz not null default now(), name_changed_at timestamptz not null default now(),
 is_banned boolean not null default false
);
create table if not exists public.admin_users (
 user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now()
);
create table if not exists public.admin_actions (
 id bigint generated by default as identity primary key, admin_user_id uuid not null references auth.users(id),
 action_type text not null, target_id text, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
alter table public.players enable row level security;alter table public.admin_users enable row level security;alter table public.admin_actions enable row level security;
drop policy if exists "Public player leaderboard read" on public.players;
create policy "Public player leaderboard read" on public.players for select to anon,authenticated using(is_banned=false);
grant select on public.players to anon,authenticated;revoke insert,update,delete on public.players from anon,authenticated;
create or replace function public.is_admin_user(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admin_users where user_id=p_user_id)$$;
create or replace function public.is_current_user_admin() returns boolean language sql stable security definer set search_path=public as $$select public.is_admin_user(auth.uid())$$;
grant execute on function public.is_current_user_admin() to authenticated;
create or replace function public.save_player_profile(p_player_id uuid,p_player_name text,p_best_score bigint,p_level integer,p_rebirths integer,p_game_version text)
returns void language plpgsql security definer set search_path=public as $$
declare clean_name text:=left(regexp_replace(trim(p_player_name),'\s+',' ','g'),16);old_name text;old_changed timestamptz;
begin
 if clean_name !~ '^[[:alnum:]_ .-]{3,16}$' then raise exception 'Nieprawidłowy nick';end if;
 if lower(clean_name) in('admin','administrator','developer','system','moderator','supabase') then raise exception 'Nazwa zarezerwowana';end if;
 select player_name,name_changed_at into old_name,old_changed from public.players where player_id=p_player_id;
 if old_name is not null and old_name<>clean_name and now()-old_changed<interval '1 hour' then raise exception 'Nick można zmienić raz na godzinę';end if;
 insert into public.players(player_id,player_name,best_score,level,rebirths,game_version,last_seen,name_changed_at)
 values(p_player_id,clean_name,greatest(0,p_best_score),greatest(1,p_level),greatest(0,p_rebirths),left(p_game_version,16),now(),now())
 on conflict(player_id) do update set player_name=excluded.player_name,best_score=greatest(public.players.best_score,excluded.best_score),level=greatest(public.players.level,excluded.level),rebirths=greatest(public.players.rebirths,excluded.rebirths),game_version=excluded.game_version,last_seen=now(),name_changed_at=case when public.players.player_name<>excluded.player_name then now() else public.players.name_changed_at end;
end$$;
grant execute on function public.save_player_profile(uuid,text,bigint,integer,integer,text) to anon,authenticated;
create or replace function public.admin_dashboard_summary() returns jsonb language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;return jsonb_build_object('players',(select count(*) from public.players),'active_24h',(select count(*) from public.players where last_seen>now()-interval '24 hours'),'feedback',(select count(*) from public.player_feedback),'banned',(select count(*) from public.players where is_banned));end$$;
create or replace function public.admin_list_players(p_query text default '') returns table(player_id uuid,player_name text,best_score bigint,level integer,rebirths integer,last_seen timestamptz,is_banned boolean) language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;return query select p.player_id,p.player_name,p.best_score,p.level,p.rebirths,p.last_seen,p.is_banned from public.players p where coalesce(p_query,'')='' or p.player_name ilike '%'||p_query||'%' or p.player_id::text ilike '%'||p_query||'%' order by p.last_seen desc limit 100;end$$;
create or replace function public.admin_list_feedback() returns setof public.player_feedback language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;return query select * from public.player_feedback order by created_at desc limit 100;end$$;
create or replace function public.admin_list_actions() returns setof public.admin_actions language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;return query select * from public.admin_actions order by created_at desc limit 100;end$$;
create or replace function public.admin_set_player_ban(p_player_id uuid,p_banned boolean) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;update public.players set is_banned=p_banned where player_id=p_player_id;insert into public.admin_actions(admin_user_id,action_type,target_id,details)values(auth.uid(),'player_ban',p_player_id::text,jsonb_build_object('banned',p_banned));end$$;
create or replace function public.admin_reset_player_score(p_player_id uuid) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;update public.players set best_score=0 where player_id=p_player_id;insert into public.admin_actions(admin_user_id,action_type,target_id)values(auth.uid(),'reset_score',p_player_id::text);end$$;
create or replace function public.admin_set_feedback_visibility(p_feedback_id bigint,p_visible boolean) returns void language plpgsql security definer set search_path=public as $$begin if not public.is_admin_user(auth.uid()) then raise exception 'Brak uprawnień';end if;update public.player_feedback set is_visible=p_visible where id=p_feedback_id;insert into public.admin_actions(admin_user_id,action_type,target_id,details)values(auth.uid(),'feedback_visibility',p_feedback_id::text,jsonb_build_object('visible',p_visible));end$$;
grant execute on function public.admin_dashboard_summary() to authenticated;grant execute on function public.admin_list_players(text) to authenticated;grant execute on function public.admin_list_feedback() to authenticated;grant execute on function public.admin_list_actions() to authenticated;grant execute on function public.admin_set_player_ban(uuid,boolean) to authenticated;grant execute on function public.admin_reset_player_score(uuid) to authenticated;grant execute on function public.admin_set_feedback_visibility(bigint,boolean) to authenticated;
create index if not exists players_score_idx on public.players(best_score desc);create index if not exists players_level_idx on public.players(level desc);create index if not exists players_rebirth_idx on public.players(rebirths desc);
