create table if not exists public.player_feedback (
  id bigint generated by default as identity primary key,
  player_id uuid not null,
  player_name text not null,
  feedback_type text not null check (feedback_type in ('opinia','bug','pomysl','balans')),
  message text not null,
  game_version text not null default 'unknown',
  is_visible boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.player_feedback enable row level security;

drop policy if exists "Public feedback read" on public.player_feedback;
create policy "Public feedback read"
on public.player_feedback
for select
to anon, authenticated
using (is_visible = true);

grant select on public.player_feedback to anon, authenticated;
revoke insert, update, delete on public.player_feedback from anon, authenticated;

create or replace function public.submit_feedback(
  p_player_id uuid,
  p_player_name text,
  p_feedback_type text,
  p_message text,
  p_game_version text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_name text;
  clean_message text;
  last_post timestamptz;
begin
  clean_name := left(trim(p_player_name), 20);
  clean_message := left(trim(p_message), 500);

  if length(clean_name) < 1 then
    clean_name := 'Gracz';
  end if;

  if p_feedback_type not in ('opinia','bug','pomysl','balans') then
    raise exception 'Nieprawidłowy typ';
  end if;

  if length(clean_message) < 5 then
    raise exception 'Wiadomość za krótka';
  end if;

  select max(created_at) into last_post
  from public.player_feedback
  where player_id = p_player_id;

  if last_post is not null and now() - last_post < interval '20 seconds' then
    raise exception 'Zbyt częste wysyłanie';
  end if;

  insert into public.player_feedback(
    player_id, player_name, feedback_type, message, game_version
  )
  values (
    p_player_id, clean_name, p_feedback_type, clean_message, left(p_game_version, 16)
  );
end;
$$;

revoke all on function public.submit_feedback(uuid,text,text,text,text) from public;
grant execute on function public.submit_feedback(uuid,text,text,text,text) to anon, authenticated;

create index if not exists player_feedback_created_idx
on public.player_feedback(created_at desc);
